// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QLsCoT7zrPvmHqp5ISWIWc6k3R6N7BA',
    appId: '1:76647369321:web:037b4f50a1c6bf1838f0f8',
    messagingSenderId: '76647369321',
    projectId: 'spydastack-notes-1b42b',
    authDomain: 'spydastack-notes-1b42b.firebaseapp.com',
    storageBucket: 'spydastack-notes-1b42b.appspot.com',
    measurementId: 'G-4134D8BE0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm7Eiwid5WQZn9T7Skl7sSz9o3eCBGgsE',
    appId: '1:76647369321:android:3a1f2b192342f5db38f0f8',
    messagingSenderId: '76647369321',
    projectId: 'spydastack-notes-1b42b',
    storageBucket: 'spydastack-notes-1b42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoS-mG6oBfUJIQLrARbzkUyHq6z7qA7zU',
    appId: '1:76647369321:ios:96bfc8b9aa2fb63f38f0f8',
    messagingSenderId: '76647369321',
    projectId: 'spydastack-notes-1b42b',
    storageBucket: 'spydastack-notes-1b42b.appspot.com',
    iosClientId: '76647369321-9it9gau1ei3uk12528lk7aqci5bdk60r.apps.googleusercontent.com',
    iosBundleId: 'com.spydastack.moodnotes',
  );
}
